# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Angular CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'  # Use your desired version of Node.js

    - name: Install dependencies
      run: npm ci  # Ensures that npm installs exactly what's in package-lock.json

    - name: Build Angular project
      run: npm run build --if-present  # Runs the build script

  lint:
    runs-on: ubuntu-latest
    needs: build  # Ensures this job runs only after the build job

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npx ng lint  # Runs the Angular linting command

  test:
    runs-on: ubuntu-latest
    needs: lint  # Ensures this job runs only after the lint job

    strategy:
      matrix:
        node-version: ['18.x', '22.x']  # Test across multiple Node.js versions if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test -- --watch=false --browsers=ChromeHeadless  # Run headless Chrome for testing





